swagger: '2.0'
info:
  version:  1.0.0
  title: RESTful接口
  description: RESTful API
  termsOfService: ""
  contact:
    name: 付红竹
    url: http://mi1024.top
    email: rootfuhz@163.com

host: localhost:8520
basePath: /api/v1
schemes:
  - https
  - http

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  APIToken:
    type: apiKey
    in: header
    name: X-API-TOKEN
security:
  - APIToken: []


paths:
  /register:
    post:
      tags:
        - 用户
      summary: 注册用户
      parameters:
      - name: user
        in: body
        required: true
        schema:
          type: object
          properties:
            name:
              description: 用户帐号
              type: string
            pwd:
              description: 登录密码
              type: string
          required:
            - name
            - pwd
      responses:
        201:
          description: 创建成功
          schema:
            $ref: '#/definitions/ApiResponse'


definitions:
  # General Response
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      data:
        type: string
      msg:
        type: string
      request:
        type: string


  ErrorResponse:
    type: object
    properties:
      error_code:
        type: integer
        format: int32
      msg:
        type: string
      request:
        type: string

  User:
    type: object
    properties:
      name:
        type: string
        minLength: 2
        maxLength: 32
      password:
        type: string
        pattern: ^[A-Za-z0-9_*&$#@]{6,22}$
        minLength: 6
        maxLength: 32
      phone:
        type: string
        pattern: ^1[0-9]{10}$
      email:
        type: string
        pattern: ^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$
    required:
    - name
    - password

