"""jpushmsg table

Revision ID: a34d9edb856d
Revises: 
Create Date: 2018-12-24 22:39:39.411256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34d9edb856d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jpush_msg',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=64), nullable=False),
    sa.Column('alert', sa.String(length=128), nullable=True),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('code', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jpush_msg')
    # ### end Alembic commands ###
