"""users table

Revision ID: f686e4f258ee
Revises: 48acaa568128
Create Date: 2019-02-27 16:04:28.952724

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f686e4f258ee'
down_revision = '48acaa568128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position_village')
    op.drop_index('parent_id', table_name='dt_area')
    op.drop_table('dt_area')
    op.drop_table('test')
    op.drop_table('user')
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=24), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('memo', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('headimg', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('last_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_ip', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('area_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('area_parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('dt_area',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('area_name', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('area_code', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('area_short', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('area_is_hot', mysql.VARCHAR(length=1), nullable=True),
    sa.Column('area_sequence', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('area_parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('init_date', mysql.DATETIME(), nullable=True),
    sa.Column('init_addr', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_comment='区域字典',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('parent_id', 'dt_area', ['area_parent_id'], unique=False)
    op.create_table('position_village',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('province_code', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('province_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city_code', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('city_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('county_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('county_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('town_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('town_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('village_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('village_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city_town_classify_code', mysql.VARCHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
